In [6]:
import numpy as np

x=[[25,1,2,1],
[20,0,0,2],
[8,1,1,5],
[15,1,0,2],
[35,0,3,1],
[40,0,5,4]]

x = np.array(x)
w = [0.3,0.2,0.5,0.1]
b = [0.1]

x*w

array([[ 7.5,  0.2,  1. ,  0.1],
       [ 6. ,  0. ,  0. ,  0.2],
       [ 2.4,  0.2,  0.5,  0.5],
       [ 4.5,  0.2,  0. ,  0.2],
       [10.5,  0. ,  1.5,  0.1],
       [12. ,  0. ,  2.5,  0.4]])

In [5]:
np.sum(x*w,axis=1)

array([ 8.8,  6.2,  3.6,  4.9, 12.1, 14.9])

In [7]:
np.dot(x,w)  #매적골    

array([ 8.8,  6.2,  3.6,  4.9, 12.1, 14.9])